# Architecture
arch: ensemble

# ===== Dataset ===== #
data: ./DATA/
set: CIFAR100
name: CIFAR10

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.256
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.875
batch_size: 256
label_smoothing: 0.1
pretrained: ['runs/resnet18-ukn-unsigned/']

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1 # Override
init: kaiming_normal
mode: fan_in
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 8