# Architecture
arch: c100ResNet18

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR100
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01
lr_policy: cosine_lr


# ===== Network training config ===== #
epochs: 200
weight_decay: 0.0001
momentum: 0.9
batch_size: 128


# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 4