# Architecture
arch: ResNet18

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: TinyImageNet
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0001
momentum: 0.9
batch_size: 128


# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 20