from data.cifar import CIFAR10
from data.imagenet import ImageNet
from data.tinyimagenet import TinyImageNet
from data.mnist import MNIST
from data.bigcifar import BigCIFAR10
from data.svhn import SVHN
from data.cifar100 import CIFAR100
from data.tinyimagenet_c import TinyImageNetC
from data.cifar10_c import CIFAR10C